### ISSUE TITLE
[Rendering] MS Teams does not scroll down, when adaptive card is sent

### ISSUE THREAD

**Issue by sueess** [microsoft/AdaptiveCards-Mobile#111]
### Target Platforms

Android

### SDK Version

1.5

### Application Name

Microsoft Teams

### Problem Description

If a new card appears in the chat, MS Teams does not scroll down. That was earlier the case and it is also the standard for any kind of messenger app. 

### Screenshots

https://github.com/microsoft/AdaptiveCards-Mobile/assets/6587992/3bfd77df-22d7-443c-b83c-d5f8ba6f4b37

### Card JSON

```JSON
It does not depend on any json, its a general issue
```

**Comment by sschoeb** [comment]
@ardlank I hope it's fine to mark you on that issue, as I think you are responsible in this topic? Let me know if I'm wrong and if there is someone else in charge of this kind of problems on teams for android. 

We got already multiple complains from our customers using our but that they are confused by this behaviour. We could not yet find any workaround. We would be happy to provide you with any further information which would help you to fix this problem.

**Comment by sschoeb** [comment]
I just tested on the latest version. Scrolling is still broken. Are we here in the correct repository or should we report this somewhere else?

**Comment by sueess** [comment]
We are getting lots of feedback to this issue, when we are talking to our users. What is the state on that scrolling issue?

**Comment by ykursav** [comment]
It is not only scroll down issue. There is also issue with horizontal scrolling. I am using table component in adaptive card, and set widths as pixels. Horizontal scroll just disappeared recently.

**Comment by sschoeb** [comment]
I still see this problem on my mobile. Is there any feedback on this? Usability is currently super bad with this bug as you are constantly scrolling within the conversation.

**Comment by ardlank** [comment]
**Adaptive Cards is now a semi private repo**

- Pull requests and issue creations will no longer be accepted and will be closed. Please send all issues with Adaptive Cards to [Microsoft Teams docs repo (msteams-docs)](https://github.com/MicrosoftDocs/msteams-docs/issues)
- Issues will be reviewed and prioritized from there
- Source code will still be available to the public.
- Packages will still be posted to the public.
