### ISSUE TITLE
[Feature Request] AndroidX migration

### ISSUE THREAD

**Issue by ThenAndNoThen** [microsoft/AdaptiveCards-Mobile#116]
### Problem Statement

There was a [PR](https://github.com/microsoft/AdaptiveCards/pull/5648) for AndroidX migration, but it's not fully covered all usage. We are still using flowbox 1.0.0 which doesn't support AndroirdX

[androidFlexboxVersion](https://github.com/search?q=repo%3Amicrosoft%2FAdaptiveCards%20androidFlexboxVersion&type=code)

### Proposed solution

Can we upgrade to flowbox >= 1.1.0 which supports AndroidX? Actually, I tried flowbox 3.0.0 locally and it works.

[flowbox 1.0.0](https://github.com/google/flexbox-layout/releases/tag/1.1.0)

I tried to build AdaptiveCard locally and send a PR myself, but failed with Cmake build error. Some steps must be missing in Android setup wiki...

**Comment by ardlank** [comment]
**Adaptive Cards is now a semi private repo**

- Pull requests and issue creations will no longer be accepted and will be closed. Please send all issues with Adaptive Cards to [Microsoft Teams docs repo (msteams-docs)](https://github.com/MicrosoftDocs/msteams-docs/issues)
- Issues will be reviewed and prioritized from there
- Source code will still be available to the public.
- Packages will still be posted to the public.

**Comment by ardlank** [comment]
**Adaptive Cards is now a semi private repo**

- Pull requests and issue creations will no longer be accepted and will be closed. Please send all issues with Adaptive Cards to [Microsoft Teams docs repo (msteams-docs)](https://github.com/MicrosoftDocs/msteams-docs/issues)
- Issues will be reviewed and prioritized from there
- Source code will still be available to the public.
- Packages will still be posted to the public.
