### ISSUE TITLE
[Rendering] No horizontal scroll teams desktop application

### ISSUE THREAD

**Issue by ykursav** [microsoft/AdaptiveCards-Mobile#145]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Microsoft Teams

### Problem Description

With recent teams update, there is no more horizontal scroll appearing in adaptive cards. 

I am using table component and users cannot horizontally scroll to see further data.

In old version of teams, scroll is there. (But 1st of July old teams will be completely deprecated)

### Screenshots

![image](https://github.com/microsoft/AdaptiveCards-Mobile/assets/13722374/52f2915f-add0-49a9-be00-eea7931c5bcd)

### Card JSON

```JSON
I can't provide.
```

**Comment by ardlank** [comment]
**Adaptive Cards is now a semi private repo**

- Pull requests and issue creations will no longer be accepted and will be closed. Please send all issues with Adaptive Cards to [Microsoft Teams docs repo (msteams-docs)](https://github.com/MicrosoftDocs/msteams-docs/issues)
- Issues will be reviewed and prioritized from there
- Source code will still be available to the public.
- Packages will still be posted to the public.
