### ISSUE TITLE
[Rendering] Iphone cuts text in adaptive cards on Microsoft Teams

### ISSUE THREAD

**Issue by sueess** [microsoft/AdaptiveCards-Mobile#151]
### Target Platforms

iOS

### SDK Version

1.5

### Application Name

Microsoft Teams

### Problem Description

Over the last year we have quite frequently problems with the iOS rendering of adaptive cards on MS Teams. At the moment text is just cut instead of a proper wrap (multiple letters are missing, see screenshots). The screenshots were made on a iPhone 13, IOS 17.5.1. 

### Screenshots

![img3](https://github.com/microsoft/AdaptiveCards-Mobile/assets/6587992/f3f8c7e6-4413-4993-9a3b-19125474bc82)
![img2](https://github.com/microsoft/AdaptiveCards-Mobile/assets/6587992/91b7b39c-ebd9-4312-91a8-8329347be08a)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.5",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "text": "Learning Package...",
              "wrap": true,
              "fontType": "Default",
              "size": "Small"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "text": "2/5",
              "fontType": "Default",
              "size": "Small",
              "horizontalAlignment": "Right"
            }
          ]
        }
      ]
    },
    {
      "type": "TextBlock",
      "text": "QUESTION",
      "height": "stretch",
      "wrap": true
    },
    {
      "type": "Input.ChoiceSet",
      "id": "sendText",
      "style": "expanded",
      "choices": [
        {
          "title": "A)",
          "value": "ANSWER"
        },
        {
          "title": "B)",
          "value": "ANSWER"
        },
        {
          "title": "C)",
          "value": "ANSWER"
        }
      ],
      "isMultiSelect": true,
      "wrap": true
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "ActionSet",
          "actions": [
            {
              "type": "Action.Submit",
              "title": "Send",
              "data": {
                "msteams": {
                  "type": "messageBack",
                  "displayText": "Send",
                  "value": {
                    "sendText": ""
                  }
                }
              },
              "msteams": {
                "feedback": {
                  "hide": true
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by ardlank** [comment]
**Adaptive Cards is now a semi private repo**

- Pull requests and issue creations will no longer be accepted and will be closed. Please send all issues with Adaptive Cards to [Microsoft Teams docs repo (msteams-docs)](https://github.com/MicrosoftDocs/msteams-docs/issues)
- Issues will be reviewed and prioritized from there
- Source code will still be available to the public.
- Packages will still be posted to the public.

**Comment by sschoeb** [comment]
@ardlank should we reopen all the closed ones in the other repo?

**Comment by sueess** [comment]
Hi @ardlank, since nobody cares about the issues we report, it's probably a good idea to close that repository. The problem is, that the other repo is as useless as this one. There are so many bugs we are reporting and customers are complaining about, but nobody is taking care. Since you are taking some action right now, are you also improving the way your work in the other repository, or should we stop reporting stuff? At least some transparency would be fair... thank you.

**Comment by MajaEffenberg** [comment]
Is there any news on this problem? We still have a problem with text being cut out instead of being wrapped properly in `Input.ChoiceSet` on iPhone (IOS 17.5.1, Microsoft Teams version 7.2.1).

### Screenshots

- iPhone
![Image](https://github.com/user-attachments/assets/8833ad85-f8a8-44ef-a0d4-0850b8fe3853)
- Android
![Image](https://github.com/user-attachments/assets/5a31aae2-d94f-4a53-904e-9d5f100271d4)

**Comment by MajaEffenberg** [comment]
Any news on this problem?
