### ISSUE TITLE
[Authoring] "We're sorry, this card couldn't be displayed" error in Teams with filtered ChoiceInputStyle

### ISSUE THREAD

**Issue by jheindr1** [microsoft/AdaptiveCards-Mobile#30]
### Target Application

Microsoft Teams

### Application Operating System

iOS

### Schema Version

1.5

### Problem Description

I'm using the Teams Power Automate connector to post an adaptive card to teams and wait for a response. I've developed the card json in the adaptive card designer and it works/renders fine but when I copy it over to my Power Automate Flow and run a test all that is delivered to the Teams chat is the "We're sorry, this card couldn't be displayed" error message. 

### Expected Outcome

![Screen Shot 2023-10-20 at 10 12 31 AM](https://github.com/microsoft/AdaptiveCards/assets/58231796/493fef32-ed51-496d-93be-1af78e9b1165)

I would expect to see this card in the teams chat, with the filtered inputchoice style allowing me to search for a value in the dropdown.

### Actual Outcome

<img width="531" alt="Screen Shot 2023-10-20 at 10 14 08 AM" src="https://github.com/microsoft/AdaptiveCards/assets/58231796/5e00a764-bc2a-4469-a086-8a68b24e6c7d">

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "version": "1.5",
    "body": [
        {
            "size": "large",
            "text": "Select a Cloud Account to View/Change Contacts",
            "weight": "bolder",
            "type": "TextBlock"
        },
        {
            "choices": [
                {
                    "title": "Account 1",
                    "value": "Account 1"
                },
                {
                    "title": "Account 2",
                    "value": "Account 2"
                },
                {
                    "title": "Account 3",
                    "value": "Account 3"
                }
            ],
            "id": "Cloud Account",
            "isRequired": true,
            "label": "Cloud Account",
            "type": "Input.ChoiceSet",
            "style": "filtered"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

**Comment by GabrielMedAlv** [comment]
The card is being rendered correctly. This issue might need to be fixed on Teams side if still persist.

![IMG_0196](https://github.com/microsoft/AdaptiveCards-Mobile/assets/130393016/a8d87d11-55fd-4b64-a522-a3687bcd1ec0)

**Comment by ardlank** [comment]
@jheindr1 please see @GabrielMedAlv comment. Is issue still present?

**Comment by marpisco** [comment]
Having the same problem here.

**Comment by marpisco** [comment]
@jheindr1 Using 1.5 didn't work so I used 1.4 and it worked. Seems like Teams is behind on Adaptive Card versions?

**Comment by HairyDrumroll** [comment]
My experience is that this works if pushed to Teams via webhook with the format as follows:

```json
{"type": "message",
"attachments": [{
        "contentType": "application/vnd.microsoft.card.adaptive",
        "contentUrl": null,
        "content": 

{"type": "AdaptiveCard",
    "version": "1.5",
    "body": [{
            "size": "large",
            "text": "Select a Cloud Account to View/Change Contacts",
            "weight": "bolder",
            "type": "TextBlock"
        },{
            "choices": [{
                    "title": "Account 1",
                    "value": "Account 1"
                },{
                    "title": "Account 2",
                    "value": "Account 2"
                },{
                    "title": "Account 3",
                    "value": "Account 3"
                }],
            "id": "Cloud Account",
            "isRequired": true,
            "label": "Cloud Account",
            "type": "Input.ChoiceSet",
            "style": "filtered"
    }],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"}

}]}

```
It does not work if you just send the AdaptiveCard via PowerAutomate unless you downgrade to version 1.4. Unfortunately, this means you miss out on some useful features in the new version, e.g.: `"isEnabled": false`.

**Comment by ardlank** [comment]
**Adaptive Cards is now a semi private repo**

- Pull requests and issue creations will no longer be accepted and will be closed. Please send all issues with Adaptive Cards to [Microsoft Teams docs repo (msteams-docs)](https://github.com/MicrosoftDocs/msteams-docs/issues)
- Issues will be reviewed and prioritized from there
- Source code will still be available to the public.
- Packages will still be posted to the public.

**Comment by eimerreis** [comment]
Also tried to post an adaptive card `version: 1.6` via webhook URL of the Workflows App, but received the message from above. 

I downgraded to `"version": "1.4"`  as described by @HairyDrumroll, then it worked.
