### ISSUE TITLE
Spacing issue in mobile

### ISSUE THREAD

**Issue by aniket0502sharma** [microsoft/AdaptiveCards-Mobile#65]
![image](https://github.com/microsoft/AdaptiveCards-Mobile/assets/137508115/fbad8833-e5cf-4527-98f5-4859f8f20842)
this is how it looks on mobile and on dekstop teams 
<img width="485" alt="image" src="https://github.com/microsoft/AdaptiveCards-Mobile/assets/137508115/a889acfa-15b2-4e67-b58a-bbd8ca018867">

I would prefer something like dekstop teams, i am attaching my adaptive card as well 

{
    "type": "AdaptiveCard",
    "version": 1.5,
    "body": [
      {
        "type": "Container",
        "isVisible": false,
        "items": [],
        "id": "headerContainer"
      },
      {
        "type": "Container",
        "id": "contentContainer",
        "items": [
          {
            "type": "Container",
            "separator": true,
            "isVisible": true,
            "items": [
              {
                "type": "ColumnSet",
                "horizontalAlignment": "Left",
                "columns": [
                  {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                      {
                        "type": "TextBlock",
                        "text": "tesr",
                        "wrap": true,
                        "horizontalAlignment": "Left",
                        "weight": "bolder",
                        "size": "medium"
                      }
                    ],
                    "horizontalAlignment": "Left"
                  },
                  {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                      {
                        "type": "TextBlock",
                        "text": "${publishedDate}",
                        "wrap": true,
                        "horizontalAlignment": "Right",
                        "isVisible": true,
                        "size": "default"
                      }
                    ],
                    "horizontalAlignment": "Right",
                    "isVisible": false
                  }
                ]
              }
            ]
          },
          {
            "type": "TextBlock",
            "text": "October 1 is a 2014 Nigerian psychological thriller film written by Tunde Babalola, produced and directed by Kunle Afolayan, and starring Sadiq Daba, Kayode Olaiya, and Demola Adedoyin. The film is set in the last months of Colonial Nigeria in 1960. It recounts the fictional story of Danladi Waziri (Daba), a police officer from Northern Nigeria, investigating a series of killings of young women in the remote Western Nigeria village of Akote just before 1 October 1960 – the date Nigeria gained independence from British colonial rule.\n\n  \n\nOctober 1 was shot with a budget of US$2 million (₦315 million in 2013) in Lagos, Ilara-Mokin, Akure, ithin six months of its release; Afolayan blamed film piracy for the film's low earnings.\n\n  \n\nOctober 1 deals with several themes, including the sexual abuse of children by religious authority",
            "wrap": true
          },
          {
            "type": "Image",
            "url": "
[https://dummyimage.com/300.png/09f/fff"](https://dummyimage.com/300.png/09f/fff%22)
,
            "isVisible": false,
            "width": "100%",
            "height": "auto",
            "msTeams": {
              "allowExpand": true
            }
          }
        ]
      },
      {
        "type": "Container",
        "isVisible": false,
        "items": [],
        "id": "footerContainer"
      }
    ],
    "msteams": {
      "width": "Full"
    }    I suspect that is happening due to multiple "/n/n" but the there should be consistency.

**Comment by ardlank** [comment]
@aniket0502sharma Mobile and Web rendering is slightly different. Create a feature request [here](https://github.com/microsoft/AdaptiveCards-Mobile/issues/new?assignees=&labels=Request%2CTriage-Needed&projects=&template=feature_request.yaml&title=%5BFeature+Request%5D+Feature+Title+Here) and we can take a look
