### ISSUE TITLE
[Android][Rendering] Memory leak issue while rendering Textblock render[Rendering]

### ISSUE THREAD

**Issue by trickcharan** [microsoft/AdaptiveCards-Mobile#80]
### Target Platforms

Android

### SDK Version

3.1.1

### Application Name

Webex

### Problem Description

The issue at hand involves the rendering of an adaptive card within a fragment or activity in Android. As expected, once we navigate away from the fragment or activity, all memory associated with the adaptive card should be released. However, this isn't happening as it should. Instead, the text block renderer in the adaptive card is retaining the reference to the fragment or activity(code reference: https://github.com/microsoft/AdaptiveCards-Mobile/blob/4e239c5e448c505d8582cfafe7983cb93e3f932c/source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java#L239C9-L256C6), preventing the full release of memory. This memory leak could potentially lead to performance issues in the application.

In addition to this, we've identified another potential memory leak in the following places

1. [DateInputHandler.java](https://github.com/microsoft/AdaptiveCards-Mobile/blob/4e239c5e448c505d8582cfafe7983cb93e3f932c/source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/DateInputHandler.java#L24)
2. [TimeInputHandler.java](https://github.com/microsoft/AdaptiveCards-Mobile/blob/4e239c5e448c505d8582cfafe7983cb93e3f932c/source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/TimeInputHandler.java#L26)

The problem arises from the storage of the fragment manager from the application which can potentially cause memory leaks.

### Screenshots

![image](https://github.com/microsoft/AdaptiveCards-Mobile/assets/29520819/609fad2a-28fc-489a-a93e-255c494c787d)

### Card JSON

```JSON
{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.0",
"body": [
{
"type": "TextBlock",
"text": "This is some text",
"size": "large"
},
{
"type": "TextBlock",
"text": "It doesn't wrap by default",
"weight": "bolder"
},
{
"type": "TextBlock",
"text": "So set wrap to true if you plan on showing a paragraph of text",
"wrap": true
},
{
"type": "TextBlock",
"text": "You can also use maxLines to prevent it from getting out of hand",
"wrap": true,
"maxLines": 2
},
{
"type": "TextBlock",
"text": "You can even draw attention to certain text with color",
"wrap": true,
"color": "attention"
}
]
}
```

### Sample Code Language

kotlin

### Sample Code

Once you run this project try to install the app and go to the second activity. Then do, dump memory. It will show two leaks.

[ButtonAndCards 2.zip](https://github.com/microsoft/AdaptiveCards/files/13914974/ButtonAndCards.2.zip)

**Comment by trickcharan** [comment]
@ardlank Any update on this issue?

**Comment by ardlank** [comment]
**Adaptive Cards is now a semi private repo**

- Pull requests and issue creations will no longer be accepted and will be closed. Please send all issues with Adaptive Cards to [Microsoft Teams docs repo (msteams-docs)](https://github.com/MicrosoftDocs/msteams-docs/issues)
- Issues will be reviewed and prioritized from there
- Source code will still be available to the public.
- Packages will still be posted to the public.
