### ISSUE TITLE
{Freeway-Bug}[Inputs.json]: Keyboard focus moves to non-interactive element in DatePicker under Due Date.

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards-Mobile#87]
### Target Platforms

Android

### SDK Version

2023.12.12.1 (85454887)

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS: Android 13
Device: S20
Screen Reader: Talkback
AdaptiveCard Android App version: 2023.12.12.1 (85454887)
Tool: Logitech Bluetooth Keyboard

**Repro Steps:**
1. Open Adaptive Cards Visualizer Application.
2. Navigate to sample cards using tab key and activate it using Enter key.
3. A dropdown would appear. Activate it using Enter key.
4. Navigate to Inputs using tab key and activate it using Enter key.
5. Navigate to the Visual tab item present at the top. A sample card would appear.
6. Navigate to the Due Date edit box inside the sample card using tab key and activate it using Enter key.
7. Navigate through the date picker using Tab keys.
8. Observe the issue.

**Actual Result:**
Keyboard focus moves to non-interactive element in Date Picker under Due Date. It goes to the current date which is a non interactive element.

**Expected Result:**
Keyboard focus shoyuld not move to non-interactive element in Date Picker under Due Date.

**User Experience:**
Keyboard users would get affected if Keyboard focus moves to non-interactive element in Date Picker under Due Date.

**WCAG Reference:**
(https://www.w3.org/WAI/WCAG21/Understanding/focus-order)

Have feedback to share on Bugs ? please tag bug as “A11yRCA” and add your feedback in the comment section

### Screenshots

![Keyboard focus is landing on the non interactive control under date picker](https://github.com/microsoft/AdaptiveCards-Mobile/assets/95913748/f3eb64cb-980b-462b-b1ff-b895042abfea)

https://github.com/microsoft/AdaptiveCards-Mobile/assets/95913748/a7d89fbe-b402-4cef-bf01-60dd81536a12

### Card JSON

```JSON
NA
```

**Comment by vagpt** [comment]
Please don't assign bug to any Dev until UnderReview Tag is added.

**Comment by MengliElmendorf137** [comment]
Close this issue, as this element is DatePickerDialog is Android Element. We do not have access to the internal textview.

**Comment by vagpt** [comment]
Hi @MengliElmendorf137,

Could you please confirm whether it is a Fluent control so that we can route this bug accordingly.
