### ISSUE TITLE
[FlightUpdateTable.Json]: Talkback focus order is moving incorrect on Passengers name and Seat number in 'FlightUpdate.json' Card.

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards-Mobile#95]
### Target Platforms

Android

### SDK Version

2023.12.12.1 (85454887)

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS: Android 13 
Device: S20 
Screen Reader: Talkback 
AdaptiveCard Android App version: 2023.12.12.1 (85454887)

**Repro Steps:**

1. Turn on the Talkback.
2. Navigate to the Visual.
3. Navigate to the sample card.
4. Using swipe gesture, swipe left to right in the card.
5. Navigate to FlightUpdate.Json button by using swipe gesture and double tap to it.
6. FlightUpdate adaptive card will be appeared.
7. Navigate to FlightUpdate card by using swipe gesture and observe the issue.

**Actual Result:**
Talkback focus is moving incorrect on Passengers name and Seat number in 'FlightUpdate.json'.
Talkback is moving on all Passengers name first then it is moving on 'Seat' number.

Currently behavior is -
Passenger -> Sarah Hum -> Jeremy Goldberg -> Evan Litvak ->Seat ->14 A -> 14B ->14C

**Expected Result:**
Talkback focus should move correct on Passenger name and seat number.
 Talkback should move like Passenger name then it's respective seat number.

Passenger -> Seat -> Sarah Hum -> 14 A.
Jeremy Goldberg -> 14B
Evan Litvak ->14C

**User Experience:**
Talkback user will be confused if proper reading order is not followed by talkback.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html

Have feedback to share on Bugs ? please tag bug as “A11yRCA” and add your feedback in the comment section

### Screenshots

https://github.com/microsoft/AdaptiveCards-Mobile/assets/95913748/496f1e55-82de-4bd7-b80a-1829e7b6b3be

![Focus order is not in sequential way](https://github.com/microsoft/AdaptiveCards-Mobile/assets/95913748/415e0593-eb71-4b0e-a503-b88d5bdf3c1f)

### Card JSON

```JSON
NA
```

**Comment by karthikgopal36** [comment]
This is not possible with the way adaptive card works now. Adaptive card elements do not accept accessibility directions.

**Comment by vagpt** [comment]
As per the comment above closing this issue as won't fix.
